export const menus = [
  {
    menuId: 1,
    menuName: '菜单管理',
    routeName: 'SystemRoute',
    routePath: '/menu-page',
    componentPath: '/system/set-routes',
    routeIcon: 'shezhi',
    parentId: 0,
    rolePermissions: '超级管理员',
    buttonPermissions: '0',
    isDelete: 0,
    description: '路由设置',
    createdAt: '2023-08-02T02:44:19.000Z',
    updatedAt: '2023-08-02T08:49:58.000Z',
    canModify: 1,
  },
  {
    menuId: 2,
    menuName: '角色管理',
    routeName: 'SystemRoute',
    routePath: '/user-page',
    componentPath: '/system/set-routes',
    routeIcon: 'shezhi',
    parentId: 0,
    rolePermissions: '超级管理员',
    buttonPermissions: '0',
    isDelete: 0,
    description: '路由设置',
    createdAt: '2023-08-02T02:44:19.000Z',
    updatedAt: '2023-08-02T08:49:58.000Z',
    canModify: 1,
  },
  {
    menuId: 3,
    menuName: '权限管理',
    routeName: 'SystemRoute',
    routePath: '/role-page',
    componentPath: '/system/set-routes',
    routeIcon: 'shezhi',
    parentId: 0,
    rolePermissions: '超级管理员',
    buttonPermissions: '0',
    isDelete: 0,
    description: '路由设置',
    createdAt: '2023-08-02T02:44:19.000Z',
    updatedAt: '2023-08-02T08:49:58.000Z',
    canModify: 1,
  },
  {
    menuId: 4,
    menuName: '系统设置',
    routeName: 'SystemRoute',
    routePath: '/system/set-routes',
    componentPath: '/system/set-routes',
    routeIcon: 'shezhi',
    parentId: 0,
    rolePermissions: '超级管理员',
    buttonPermissions: '0',
    isDelete: 0,
    description: '路由设置',
    createdAt: '2023-08-02T02:44:19.000Z',
    updatedAt: '2023-08-02T08:49:58.000Z',
    canModify: 1,
  },
  {
    menuId: 5,
    menuName: '系统设置',
    routeName: 'SystemRoute',
    routePath: '/system/set-routes',
    componentPath: '/system/set-routes',
    routeIcon: 'shezhi',
    parentId: 0,
    rolePermissions: '超级管理员',
    buttonPermissions: '0',
    isDelete: 0,
    description: '路由设置',
    createdAt: '2023-08-02T02:44:19.000Z',
    updatedAt: '2023-08-02T08:49:58.000Z',
    canModify: 1,
  },
];
